language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t bcrivelaro/dockerized-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bcrivelaro/dockerized-react npm run test
